/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Timestamp = IDL.Int;
export const TaskId = IDL.Nat;
export const URL = IDL.Text;
export const ProofType = IDL.Variant({
  'textNote' : IDL.Text,
  'checklistConfirmation' : IDL.Vec(IDL.Bool),
  'timedSessionLog' : IDL.Nat,
  'photoUpload' : URL,
});
export const Completion = IDL.Record({
  'completionTime' : Timestamp,
  'taskId' : TaskId,
  'proof' : ProofType,
  'reflection' : IDL.Text,
});
export const ReminderId = IDL.Nat;
export const Reminder = IDL.Record({
  'id' : ReminderId,
  'scheduledTime' : Timestamp,
  'taskId' : TaskId,
  'isRereminder' : IDL.Bool,
});
export const Badge = IDL.Text;
export const Coins = IDL.Nat;
export const XP = IDL.Nat;
export const Reward = IDL.Record({
  'levelUp' : IDL.Bool,
  'badges' : IDL.Vec(Badge),
  'streakBonus' : IDL.Bool,
  'coinsGained' : Coins,
  'xpGained' : XP,
});
export const Image = IDL.Vec(IDL.Nat8);
export const Level = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'totalXP' : XP,
  'coins' : Coins,
  'badges' : IDL.Vec(Badge),
  'level' : Level,
  'avatarUrl' : IDL.Opt(ExternalBlob),
  'streakCount' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Recurrence = IDL.Variant({
  'custom' : IDL.Vec(Timestamp),
  'daily' : IDL.Null,
  'weekly' : IDL.Vec(IDL.Bool),
});
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : TaskId,
  'title' : IDL.Text,
  'gracePeriod' : IDL.Nat,
  'description' : IDL.Text,
  'recurrence' : Recurrence,
  'creationTime' : Timestamp,
  'targetTimes' : IDL.Vec(Timestamp),
  'category' : IDL.Text,
  'estimatedDuration' : IDL.Opt(IDL.Nat),
  'priority' : Priority,
  'dbBlobImage' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCompletion' : IDL.Func([Completion], [], []),
  'addReminder' : IDL.Func([Reminder], [], []),
  'addReward' : IDL.Func([Reward], [], []),
  'addTaskImage' : IDL.Func([TaskId, Image], [], []),
  'adminGetUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTask' : IDL.Func([Task], [TaskId], []),
  'deleteTask' : IDL.Func([TaskId], [], []),
  'getAverageCompletionTime' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Record({ 'avgTime' : IDL.Float64, 'nTasks' : IDL.Nat })],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompletions' : IDL.Func([], [IDL.Vec(Completion)], ['query']),
  'getReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
  'getRewardHistory' : IDL.Func([], [IDL.Vec(Reward)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserStatsByLevel' : IDL.Func(
      [Level, Level],
      [
        IDL.Record({
          'XP' : XP,
          'started' : IDL.Nat,
          'completed' : IDL.Nat,
          'Coins' : Coins,
          'inProgress' : IDL.Nat,
          'failed' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserTask' : IDL.Func([TaskId], [Task], ['query']),
  'getUserTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'initializeUser' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateTask' : IDL.Func([Task], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Timestamp = IDL.Int;
  const TaskId = IDL.Nat;
  const URL = IDL.Text;
  const ProofType = IDL.Variant({
    'textNote' : IDL.Text,
    'checklistConfirmation' : IDL.Vec(IDL.Bool),
    'timedSessionLog' : IDL.Nat,
    'photoUpload' : URL,
  });
  const Completion = IDL.Record({
    'completionTime' : Timestamp,
    'taskId' : TaskId,
    'proof' : ProofType,
    'reflection' : IDL.Text,
  });
  const ReminderId = IDL.Nat;
  const Reminder = IDL.Record({
    'id' : ReminderId,
    'scheduledTime' : Timestamp,
    'taskId' : TaskId,
    'isRereminder' : IDL.Bool,
  });
  const Badge = IDL.Text;
  const Coins = IDL.Nat;
  const XP = IDL.Nat;
  const Reward = IDL.Record({
    'levelUp' : IDL.Bool,
    'badges' : IDL.Vec(Badge),
    'streakBonus' : IDL.Bool,
    'coinsGained' : Coins,
    'xpGained' : XP,
  });
  const Image = IDL.Vec(IDL.Nat8);
  const Level = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'totalXP' : XP,
    'coins' : Coins,
    'badges' : IDL.Vec(Badge),
    'level' : Level,
    'avatarUrl' : IDL.Opt(ExternalBlob),
    'streakCount' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Recurrence = IDL.Variant({
    'custom' : IDL.Vec(Timestamp),
    'daily' : IDL.Null,
    'weekly' : IDL.Vec(IDL.Bool),
  });
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : TaskId,
    'title' : IDL.Text,
    'gracePeriod' : IDL.Nat,
    'description' : IDL.Text,
    'recurrence' : Recurrence,
    'creationTime' : Timestamp,
    'targetTimes' : IDL.Vec(Timestamp),
    'category' : IDL.Text,
    'estimatedDuration' : IDL.Opt(IDL.Nat),
    'priority' : Priority,
    'dbBlobImage' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCompletion' : IDL.Func([Completion], [], []),
    'addReminder' : IDL.Func([Reminder], [], []),
    'addReward' : IDL.Func([Reward], [], []),
    'addTaskImage' : IDL.Func([TaskId, Image], [], []),
    'adminGetUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTask' : IDL.Func([Task], [TaskId], []),
    'deleteTask' : IDL.Func([TaskId], [], []),
    'getAverageCompletionTime' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Record({ 'avgTime' : IDL.Float64, 'nTasks' : IDL.Nat })],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompletions' : IDL.Func([], [IDL.Vec(Completion)], ['query']),
    'getReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
    'getRewardHistory' : IDL.Func([], [IDL.Vec(Reward)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserStatsByLevel' : IDL.Func(
        [Level, Level],
        [
          IDL.Record({
            'XP' : XP,
            'started' : IDL.Nat,
            'completed' : IDL.Nat,
            'Coins' : Coins,
            'inProgress' : IDL.Nat,
            'failed' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserTask' : IDL.Func([TaskId], [Task], ['query']),
    'getUserTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'initializeUser' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateTask' : IDL.Func([Task], [], []),
  });
};

export const init = ({ IDL }) => { return []; };