/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Badge = string;
export type Coins = bigint;
export interface Completion {
  'completionTime' : Timestamp,
  'taskId' : TaskId,
  'proof' : ProofType,
  'reflection' : string,
}
export type ExternalBlob = Uint8Array;
export type Image = Uint8Array;
export type Level = bigint;
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type ProofType = { 'textNote' : string } |
  { 'checklistConfirmation' : Array<boolean> } |
  { 'timedSessionLog' : bigint } |
  { 'photoUpload' : URL };
export type Recurrence = { 'custom' : Array<Timestamp> } |
  { 'daily' : null } |
  { 'weekly' : Array<boolean> };
export interface Reminder {
  'id' : ReminderId,
  'scheduledTime' : Timestamp,
  'taskId' : TaskId,
  'isRereminder' : boolean,
}
export type ReminderId = bigint;
export interface Reward {
  'levelUp' : boolean,
  'badges' : Array<Badge>,
  'streakBonus' : boolean,
  'coinsGained' : Coins,
  'xpGained' : XP,
}
export interface Task {
  'id' : TaskId,
  'title' : string,
  'gracePeriod' : bigint,
  'description' : string,
  'recurrence' : Recurrence,
  'creationTime' : Timestamp,
  'targetTimes' : Array<Timestamp>,
  'category' : string,
  'estimatedDuration' : [] | [bigint],
  'priority' : Priority,
  'dbBlobImage' : [] | [ExternalBlob],
}
export type TaskId = bigint;
export type Timestamp = bigint;
export type URL = string;
export interface UserProfile {
  'displayName' : string,
  'totalXP' : XP,
  'coins' : Coins,
  'badges' : Array<Badge>,
  'level' : Level,
  'avatarUrl' : [] | [ExternalBlob],
  'streakCount' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type XP = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCompletion' : ActorMethod<[Completion], undefined>,
  'addReminder' : ActorMethod<[Reminder], undefined>,
  'addReward' : ActorMethod<[Reward], undefined>,
  'addTaskImage' : ActorMethod<[TaskId, Image], undefined>,
  'adminGetUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTask' : ActorMethod<[Task], TaskId>,
  'deleteTask' : ActorMethod<[TaskId], undefined>,
  'getAverageCompletionTime' : ActorMethod<
    [bigint, bigint],
    { 'avgTime' : number, 'nTasks' : bigint }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompletions' : ActorMethod<[], Array<Completion>>,
  'getReminders' : ActorMethod<[], Array<Reminder>>,
  'getRewardHistory' : ActorMethod<[], Array<Reward>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserStatsByLevel' : ActorMethod<
    [Level, Level],
    {
      'XP' : XP,
      'started' : bigint,
      'completed' : bigint,
      'Coins' : Coins,
      'inProgress' : bigint,
      'failed' : bigint,
    }
  >,
  'getUserTask' : ActorMethod<[TaskId], Task>,
  'getUserTasks' : ActorMethod<[], Array<Task>>,
  'initializeUser' : ActorMethod<[string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateTask' : ActorMethod<[Task], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];