/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type URL = string;
export type Level = bigint;
export type Timestamp = bigint;
export interface Reward {
    levelUp: boolean;
    badges: Array<Badge>;
    streakBonus: boolean;
    coinsGained: Coins;
    xpGained: XP;
}
export type ReminderId = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Task {
    id: TaskId;
    title: string;
    gracePeriod: bigint;
    description: string;
    recurrence: Recurrence;
    creationTime: Timestamp;
    targetTimes: Array<Timestamp>;
    category: string;
    estimatedDuration?: bigint;
    priority: Priority;
    dbBlobImage?: ExternalBlob;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type Coins = bigint;
export type Badge = string;
export type ProofType = {
    __kind__: "textNote";
    textNote: string;
} | {
    __kind__: "checklistConfirmation";
    checklistConfirmation: Array<boolean>;
} | {
    __kind__: "timedSessionLog";
    timedSessionLog: bigint;
} | {
    __kind__: "photoUpload";
    photoUpload: URL;
};
export type Recurrence = {
    __kind__: "custom";
    custom: Array<Timestamp>;
} | {
    __kind__: "daily";
    daily: null;
} | {
    __kind__: "weekly";
    weekly: Array<boolean>;
};
export interface Reminder {
    id: ReminderId;
    scheduledTime: Timestamp;
    taskId: TaskId;
    isRereminder: boolean;
}
export interface Completion {
    completionTime: Timestamp;
    taskId: TaskId;
    proof: ProofType;
    reflection: string;
}
export type XP = bigint;
export type TaskId = bigint;
export type Image = Uint8Array;
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    displayName: string;
    totalXP: XP;
    coins: Coins;
    badges: Array<Badge>;
    level: Level;
    avatarUrl?: ExternalBlob;
    streakCount: bigint;
}
export enum Priority {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCompletion(completion: Completion): Promise<void>;
    addReminder(reminder: Reminder): Promise<void>;
    addReward(reward: Reward): Promise<void>;
    addTaskImage(taskId: TaskId, image: Image): Promise<void>;
    adminGetUserProfile(user: Principal): Promise<UserProfile | null>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createTask(task: Task): Promise<TaskId>;
    deleteTask(taskId: TaskId): Promise<void>;
    getAverageCompletionTime(startTime: bigint, endTime: bigint): Promise<{
        avgTime: number;
        nTasks: bigint;
    }>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCompletions(): Promise<Array<Completion>>;
    getReminders(): Promise<Array<Reminder>>;
    getRewardHistory(): Promise<Array<Reward>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserStatsByLevel(minLevel: Level, maxLevel: Level): Promise<{
        XP: XP;
        started: bigint;
        completed: bigint;
        Coins: Coins;
        inProgress: bigint;
        failed: bigint;
    }>;
    getUserTask(taskId: TaskId): Promise<Task>;
    getUserTasks(): Promise<Array<Task>>;
    initializeUser(displayName: string): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateTask(task: Task): Promise<void>;
}
import type { Badge as _Badge, Coins as _Coins, Completion as _Completion, ExternalBlob as _ExternalBlob, Level as _Level, Priority as _Priority, ProofType as _ProofType, Recurrence as _Recurrence, Task as _Task, TaskId as _TaskId, Timestamp as _Timestamp, URL as _URL, UserProfile as _UserProfile, UserRole as _UserRole, XP as _XP, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCompletion(arg0: Completion): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCompletion(to_candid_Completion_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCompletion(to_candid_Completion_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addReminder(arg0: Reminder): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReminder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReminder(arg0);
            return result;
        }
    }
    async addReward(arg0: Reward): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReward(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReward(arg0);
            return result;
        }
    }
    async addTaskImage(arg0: TaskId, arg1: Image): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTaskImage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTaskImage(arg0, arg1);
            return result;
        }
    }
    async adminGetUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createTask(arg0: Task): Promise<TaskId> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(await to_candid_Task_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(await to_candid_Task_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteTask(arg0: TaskId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async getAverageCompletionTime(arg0: bigint, arg1: bigint): Promise<{
        avgTime: number;
        nTasks: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAverageCompletionTime(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAverageCompletionTime(arg0, arg1);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompletions(): Promise<Array<Completion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompletions();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompletions();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReminders(): Promise<Array<Reminder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReminders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReminders();
            return result;
        }
    }
    async getRewardHistory(): Promise<Array<Reward>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRewardHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRewardHistory();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserStatsByLevel(arg0: Level, arg1: Level): Promise<{
        XP: XP;
        started: bigint;
        completed: bigint;
        Coins: Coins;
        inProgress: bigint;
        failed: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserStatsByLevel(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserStatsByLevel(arg0, arg1);
            return result;
        }
    }
    async getUserTask(arg0: TaskId): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserTask(arg0);
                return from_candid_Task_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserTask(arg0);
            return from_candid_Task_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserTasks();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserTasks();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeUser(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n40(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n40(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateTask(arg0: Task): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(await to_candid_Task_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(await to_candid_Task_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Completion_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Completion): Completion {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Priority_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Priority): Priority {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_ProofType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProofType): ProofType {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Recurrence_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Recurrence): Recurrence {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
async function from_candid_Task_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Promise<Task> {
    return await from_candid_record_n34(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n13(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    totalXP: _XP;
    coins: _Coins;
    badges: Array<_Badge>;
    level: _Level;
    avatarUrl: [] | [_ExternalBlob];
    streakCount: bigint;
}): Promise<{
    displayName: string;
    totalXP: XP;
    coins: Coins;
    badges: Array<Badge>;
    level: Level;
    avatarUrl?: ExternalBlob;
    streakCount: bigint;
}> {
    return {
        displayName: value.displayName,
        totalXP: value.totalXP,
        coins: value.coins,
        badges: value.badges,
        level: value.level,
        avatarUrl: record_opt_to_undefined(await from_candid_opt_n15(_uploadFile, _downloadFile, value.avatarUrl)),
        streakCount: value.streakCount
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completionTime: _Timestamp;
    taskId: _TaskId;
    proof: _ProofType;
    reflection: string;
}): {
    completionTime: Timestamp;
    taskId: TaskId;
    proof: ProofType;
    reflection: string;
} {
    return {
        completionTime: value.completionTime,
        taskId: value.taskId,
        proof: from_candid_ProofType_n31(_uploadFile, _downloadFile, value.proof),
        reflection: value.reflection
    };
}
async function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TaskId;
    title: string;
    gracePeriod: bigint;
    description: string;
    recurrence: _Recurrence;
    creationTime: _Timestamp;
    targetTimes: Array<_Timestamp>;
    category: string;
    estimatedDuration: [] | [bigint];
    priority: _Priority;
    dbBlobImage: [] | [_ExternalBlob];
}): Promise<{
    id: TaskId;
    title: string;
    gracePeriod: bigint;
    description: string;
    recurrence: Recurrence;
    creationTime: Timestamp;
    targetTimes: Array<Timestamp>;
    category: string;
    estimatedDuration?: bigint;
    priority: Priority;
    dbBlobImage?: ExternalBlob;
}> {
    return {
        id: value.id,
        title: value.title,
        gracePeriod: value.gracePeriod,
        description: value.description,
        recurrence: from_candid_Recurrence_n35(_uploadFile, _downloadFile, value.recurrence),
        creationTime: value.creationTime,
        targetTimes: value.targetTimes,
        category: value.category,
        estimatedDuration: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.estimatedDuration)),
        priority: from_candid_Priority_n37(_uploadFile, _downloadFile, value.priority),
        dbBlobImage: record_opt_to_undefined(await from_candid_opt_n15(_uploadFile, _downloadFile, value.dbBlobImage))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    textNote: string;
} | {
    checklistConfirmation: Array<boolean>;
} | {
    timedSessionLog: bigint;
} | {
    photoUpload: _URL;
}): {
    __kind__: "textNote";
    textNote: string;
} | {
    __kind__: "checklistConfirmation";
    checklistConfirmation: Array<boolean>;
} | {
    __kind__: "timedSessionLog";
    timedSessionLog: bigint;
} | {
    __kind__: "photoUpload";
    photoUpload: URL;
} {
    return "textNote" in value ? {
        __kind__: "textNote",
        textNote: value.textNote
    } : "checklistConfirmation" in value ? {
        __kind__: "checklistConfirmation",
        checklistConfirmation: value.checklistConfirmation
    } : "timedSessionLog" in value ? {
        __kind__: "timedSessionLog",
        timedSessionLog: value.timedSessionLog
    } : "photoUpload" in value ? {
        __kind__: "photoUpload",
        photoUpload: value.photoUpload
    } : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    custom: Array<_Timestamp>;
} | {
    daily: null;
} | {
    weekly: Array<boolean>;
}): {
    __kind__: "custom";
    custom: Array<Timestamp>;
} | {
    __kind__: "daily";
    daily: null;
} | {
    __kind__: "weekly";
    weekly: Array<boolean>;
} {
    return "custom" in value ? {
        __kind__: "custom",
        custom: value.custom
    } : "daily" in value ? {
        __kind__: "daily",
        daily: value.daily
    } : "weekly" in value ? {
        __kind__: "weekly",
        weekly: value.weekly
    } : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): Priority {
    return "low" in value ? Priority.low : "high" in value ? Priority.high : "medium" in value ? Priority.medium : value;
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Completion>): Array<Completion> {
    return value.map((x)=>from_candid_Completion_n29(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Promise<Array<Task>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Task_n33(_uploadFile, _downloadFile, x)));
}
function to_candid_Completion_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Completion): _Completion {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Priority_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): _Priority {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_ProofType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProofType): _ProofType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Recurrence_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Recurrence): _Recurrence {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
async function to_candid_Task_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Task): Promise<_Task> {
    return await to_candid_record_n20(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: TaskId;
    title: string;
    gracePeriod: bigint;
    description: string;
    recurrence: Recurrence;
    creationTime: Timestamp;
    targetTimes: Array<Timestamp>;
    category: string;
    estimatedDuration?: bigint;
    priority: Priority;
    dbBlobImage?: ExternalBlob;
}): Promise<{
    id: _TaskId;
    title: string;
    gracePeriod: bigint;
    description: string;
    recurrence: _Recurrence;
    creationTime: _Timestamp;
    targetTimes: Array<_Timestamp>;
    category: string;
    estimatedDuration: [] | [bigint];
    priority: _Priority;
    dbBlobImage: [] | [_ExternalBlob];
}> {
    return {
        id: value.id,
        title: value.title,
        gracePeriod: value.gracePeriod,
        description: value.description,
        recurrence: to_candid_Recurrence_n21(_uploadFile, _downloadFile, value.recurrence),
        creationTime: value.creationTime,
        targetTimes: value.targetTimes,
        category: value.category,
        estimatedDuration: value.estimatedDuration ? candid_some(value.estimatedDuration) : candid_none(),
        priority: to_candid_Priority_n23(_uploadFile, _downloadFile, value.priority),
        dbBlobImage: value.dbBlobImage ? candid_some(await to_candid_ExternalBlob_n25(_uploadFile, _downloadFile, value.dbBlobImage)) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    totalXP: XP;
    coins: Coins;
    badges: Array<Badge>;
    level: Level;
    avatarUrl?: ExternalBlob;
    streakCount: bigint;
}): Promise<{
    displayName: string;
    totalXP: _XP;
    coins: _Coins;
    badges: Array<_Badge>;
    level: _Level;
    avatarUrl: [] | [_ExternalBlob];
    streakCount: bigint;
}> {
    return {
        displayName: value.displayName,
        totalXP: value.totalXP,
        coins: value.coins,
        badges: value.badges,
        level: value.level,
        avatarUrl: value.avatarUrl ? candid_some(await to_candid_ExternalBlob_n25(_uploadFile, _downloadFile, value.avatarUrl)) : candid_none(),
        streakCount: value.streakCount
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completionTime: Timestamp;
    taskId: TaskId;
    proof: ProofType;
    reflection: string;
}): {
    completionTime: _Timestamp;
    taskId: _TaskId;
    proof: _ProofType;
    reflection: string;
} {
    return {
        completionTime: value.completionTime,
        taskId: value.taskId,
        proof: to_candid_ProofType_n10(_uploadFile, _downloadFile, value.proof),
        reflection: value.reflection
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "textNote";
    textNote: string;
} | {
    __kind__: "checklistConfirmation";
    checklistConfirmation: Array<boolean>;
} | {
    __kind__: "timedSessionLog";
    timedSessionLog: bigint;
} | {
    __kind__: "photoUpload";
    photoUpload: URL;
}): {
    textNote: string;
} | {
    checklistConfirmation: Array<boolean>;
} | {
    timedSessionLog: bigint;
} | {
    photoUpload: _URL;
} {
    return value.__kind__ === "textNote" ? {
        textNote: value.textNote
    } : value.__kind__ === "checklistConfirmation" ? {
        checklistConfirmation: value.checklistConfirmation
    } : value.__kind__ === "timedSessionLog" ? {
        timedSessionLog: value.timedSessionLog
    } : value.__kind__ === "photoUpload" ? {
        photoUpload: value.photoUpload
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "custom";
    custom: Array<Timestamp>;
} | {
    __kind__: "daily";
    daily: null;
} | {
    __kind__: "weekly";
    weekly: Array<boolean>;
}): {
    custom: Array<_Timestamp>;
} | {
    daily: null;
} | {
    weekly: Array<boolean>;
} {
    return value.__kind__ === "custom" ? {
        custom: value.custom
    } : value.__kind__ === "daily" ? {
        daily: value.daily
    } : value.__kind__ === "weekly" ? {
        weekly: value.weekly
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == Priority.low ? {
        low: null
    } : value == Priority.high ? {
        high: null
    } : value == Priority.medium ? {
        medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
